# Generated by Django 4.0.4 on 2022-04-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersignin', '0003_registeruserss_delete_registrateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruserss',
            name='mobileno',
            field=models.IntegerField(max_length=10),
        ),
    ]
