# Generated by Django 4.0.4 on 2022-04-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersignin', '0004_alter_registeruserss_mobileno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registeruserss',
            new_name='registerUsers',
        ),
    ]
