# Generated by Django 4.0.4 on 2022-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersignin', '0005_rename_registeruserss_registerusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
