# Generated by Django 4.0.4 on 2022-04-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersignin', '0008_register_delete_registerusers_alter_signuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signuser',
            options={'managed': False},
        ),
    ]
